name = "Specific"
uuid = "0fb2cfb0-ef68-4639-af2f-cb92dac991ae"
authors = ["Amin Yahyaabadi"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
